### ISSUE TITLE
Won't work :-(

### ISSUE THREAD

**Issue by paunadeu** [leandromoreira/clappr-stats#2] opened 2016-07-18 08:17 UTC
I initialize player this:

```
new Clappr.Player(
            {
                source: this.canal.streaming_url,
                poster: this.epgPoster,
                plugins: [LevelSelector, ChromecastPlugin, ClapprStats],
                levelSelectorConfig: {
                    title: 'Qualitat',
                    labels: {
                        2: 'Alta', // 500kbps
                        1: 'Mitja', // 240kbps
                        0: 'Baixa', // 120kbps
                    }
                },
                parentId: "#player",
                chromecast: {
                    appId: undefined,
                    contentType: 'video/mp4',
                    media: {
                        type: ChromecastPlugin.Movie,
                        title: this.canal.description,
                        subtitle: this.currentEpgDescription,
                    }
                },
                autoPlay: true,
                width: '100%',
                clapprStats: {
                    runEach: 1000,
                    onReport: (metrics) => {console.log(metrics)},
                    //uriToMeasureLatency: 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Transparent.gif'
                }
            });
```

Console don't show nothing. Any way to find more?
The streaming URL is a m3u8 playlist.

Regards

**Comment by leandromoreira** [comment] 2016-07-18 18:48
@paunadeu I just tested at http://cdn.clappr.io/ and it seems to be working.

```javascript
var playerElement = document.getElementById("player-wrapper");

var player = new Clappr.Player({
  source: 'http://clappr.io/highline.mp4',
  plugins:[ClapprStats],
  baseUrl: '/latest',
  poster: 'http://clappr.io/poster.png',
  mute: true,
  height: 360,
  width: 640
});

player.attachTo(playerElement);

```

**Comment by leandromoreira** [comment] 2016-07-18 18:50
is it shows any error?

**Comment by paunadeu** [comment] 2016-07-19 07:55
Hello Leandro, nothing errors. I'll try to enable Clappr Debug and update you,.

**Comment by paunadeu** [comment] 2016-07-19 08:29
```
XHR finished loading: GET "http://10.0.0.16:8100/build/pages/channel/channel.html".
Native: tried calling StatusBar.show, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator
Constructor determined is false a cordova App
Object {id: 6, description: "LaSexta", logo: "https://tv.company-name.com.cat/logos/180x180/jpg/lasexta.jpg", channel_string: "lasexta.stream", channel_type: "sd"…}
[debug][MediaControl] mediacontrol:notplaying
[debug][MediaControl] mediacontrol:rendered
[debug][Container] container:mediacontrol:disable
[debug][e] core:containers:created
[debug][hls] playback:ready hls
[debug][Container] container:ready Container
[debug][Container] container:volume 0 Container
[debug][MediaControl] mediacontrol:notplaying
[debug][MediaControl] mediacontrol:notplaying
[debug][MediaControl] mediacontrol:rendered
[debug][Container] container:dvr false
[debug][MediaControl] mediacontrol:hide MediaControl
[debug][Container] container:mediacontrol:hide
[debug][MediaControl] mediacontrol:containerchanged
[debug][Container] container:volume 0 Container
[debug][MediaControl] mediacontrol:notplaying
[debug][MediaControl] mediacontrol:rendered
[debug][t] 1:resize Object {width: "100%", height: 360}
[debug][e] core:ready
[debug][e] ready
Font from origin 'https://tv.company-name.com.cat' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://10.0.0.16:8100' is therefore not allowed access.
XHR finished loading: GET "chrome-extension://boadgeojelhgndaghljhdicfkmllpafd/cast_sender.js".
XHR finished loading: GET "https://tv-api.company-name.com.cat/channel/search/byId/6/epg".
Unrecognized Content-Security-Policy directive 'child-src:*'.

XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/playlist.m3u8?fibraca…ttime=1468916765&company-name.comhash=ntZkTf8pJX_KCiVV4akES2L5xP_ZdrKYd_vMiM4sfDM=".
[debug][hls] playback:levels:available [Object, Object]
[debug][hls] playback:levels:switch:end
[debug][hls] playback:level:switch Object {level: 0}
[debug][hls] playback:highdefinitionupdate false
[debug][Container] container:highdefinitionupdate false
[debug][hls] playback:bitrate Object {height: 360, width: 640, bandwidth: undefined, bitrate: 750000, level: 0}
[debug][Container] container:bitrate Object {height: 360, width: 640, bandwidth: undefined, bitrate: 750000, level: 0}
XHR finished loading: GET "https://tv-api.company-name.com.cat/epg/search/availableByIdAndDate/6/today".
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/chunklist_w307927015_…hdGhhc2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=.m3u8".
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][MediaControl] mediacontrol:notplaying
[debug][MediaControl] mediacontrol:rendered
[debug][hls] playback:levels:available [Object, Object]
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/media_w307927015_b750…c2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=_297226.ts".
[debug][hls] playback:fragment:loaded Object {payload: ArrayBuffer, frag: Object, stats: Object}
[debug][chromecast] init success
[debug][chromecast] receiver list empty
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][MediaControl] mediacontrol:notplaying
[debug][MediaControl] mediacontrol:rendered
[debug][hls] playback:bufferfull hls
[debug][Container] container:state:bufferfull Container
[debug][hls] playback:loadedmetadata Object {duration: 5.76, data: Event}
[debug][Container] container:loadedmetadata Object {duration: 5.76, data: Event}
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][hls] playback:levels:switch:end
[debug][hls] playback:level:switch Object {level: 1}
[debug][hls] playback:highdefinitionupdate true
[debug][Container] container:highdefinitionupdate true
[debug][hls] playback:bitrate Object {height: 576, width: 768, bandwidth: undefined, bitrate: 2097152, level: 1}
[debug][Container] container:bitrate Object {height: 576, width: 768, bandwidth: undefined, bitrate: 2097152, level: 1}
[debug][t] 1:resize Object {width: 2548, height: 360}
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/chunklist_w307927015_…hdGhhc2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=.m3u8".
[debug][hls] playback:levels:available [Object, Object]
[debug][hls] playback:buffering hls
[debug][Container] container:state:buffering Container
[debug][hls] playback:bufferfull hls
[debug][Container] container:state:bufferfull Container
[debug][hls] playback:play
[debug][Container] container:play Container
[debug][Container] container:mediacontrol:enable
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][MediaControl] mediacontrol:playing
[debug][e] play
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/media_w307927015_b209…c2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=_297227.ts".
[debug][hls] playback:fragment:loaded Object {payload: ArrayBuffer, frag: Object, stats: Object}
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/media_w307927015_b209…c2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=_297228.ts".
[debug][hls] playback:fragment:loaded Object {payload: ArrayBuffer, frag: Object, stats: Object}
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][MediaControl] mediacontrol:hide MediaControl
[debug][Container] container:mediacontrol:hide
[debug][t] 1:resize Object {width: 2548, height: 545}
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/chunklist_w307927015_…hdGhhc2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=.m3u8".
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][hls] playback:levels:available [Object, Object]
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/media_w307927015_b209…c2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=_297229.ts".
[debug][hls] playback:fragment:loaded Object {payload: ArrayBuffer, frag: Object, stats: Object}
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][Container] container:stats:report Object {startupTime: 5, rebuffers: 1, rebufferingTime: 0, watchingTime: 5003, height: 576…}
XHR finished loading: GET "https://tv-api.company-name.com.cat/stats/add/%7B%22uriId%22:%22eyJpdiI6Ik1QMFdLVTN…QwYzM0NzQzYmUzMjkxZWQ4MzE4Y2I5NmM2In0=%22,%22tvFrontendTvChannelId%22:6%7D".
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/chunklist_w307927015_…hdGhhc2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=.m3u8".
[debug][hls] playback:levels:available [Object, Object]
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/media_w307927015_b209…c2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=_297230.ts".
[debug][hls] playback:fragment:loaded Object {payload: ArrayBuffer, frag: Object, stats: Object}
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/media_w307927015_b209…c2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=_297231.ts".
[debug][hls] playback:fragment:loaded Object {payload: ArrayBuffer, frag: Object, stats: Object}
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/chunklist_w307927015_…hdGhhc2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=.m3u8".
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][hls] playback:levels:available [Object, Object]
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/media_w307927015_b209…c2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=_297232.ts".
[debug][hls] playback:fragment:loaded Object {payload: ArrayBuffer, frag: Object, stats: Object}
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][Container] container:stats:report Object {startupTime: 5, rebuffers: 1, rebufferingTime: 0, watchingTime: 10000, height: 576…}
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/chunklist_w307927015_…hdGhhc2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=.m3u8".
[debug][hls] playback:levels:available [Object, Object]
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/media_w307927015_b209…c2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=_297233.ts".
[debug][hls] playback:fragment:loaded Object {payload: ArrayBuffer, frag: Object, stats: Object}
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/media_w307927015_b209…c2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=_297234.ts".
[debug][hls] playback:fragment:loaded Object {payload: ArrayBuffer, frag: Object, stats: Object}
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/chunklist_w307927015_…hdGhhc2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=.m3u8".
[debug][hls] playback:levels:available [Object, Object]
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][Container] container:stats:report Object {startupTime: 5, rebuffers: 1, rebufferingTime: 0, watchingTime: 15000, height: 576…}
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/media_w307927015_b209…c2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=_297235.ts".
[debug][hls] playback:fragment:loaded Object {payload: ArrayBuffer, frag: Object, stats: Object}
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/chunklist_w307927015_…hdGhhc2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=.m3u8".
[debug][hls] playback:levels:available [Object, Object]
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/media_w307927015_b209…c2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=_297236.ts".
[debug][hls] playback:fragment:loaded Object {payload: ArrayBuffer, frag: Object, stats: Object}
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/media_w307927015_b209…c2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=_297237.ts".
[debug][hls] playback:fragment:loaded Object {payload: ArrayBuffer, frag: Object, stats: Object}
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][Container] container:stats:report Object {startupTime: 5, rebuffers: 1, rebufferingTime: 0, watchingTime: 20001, height: 576…}
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/chunklist_w307927015_…hdGhhc2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=.m3u8".
[debug][hls] playback:levels:available [Object, Object]
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/media_w307927015_b209…c2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=_297238.ts".
[debug][hls] playback:fragment:loaded Object {payload: ArrayBuffer, frag: Object, stats: Object}
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][Container] container:mouseenter
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][Container] container:mouseleave
[debug][MediaControl] mediacontrol:hide MediaControl
[debug][Container] container:mediacontrol:hide
[debug][Container] container:mouseenter
[debug][MediaControl] mediacontrol:show MediaControl
[debug][Container] container:mediacontrol:show
[debug][Container] container:mouseleave
[debug][MediaControl] mediacontrol:hide MediaControl
[debug][Container] container:mediacontrol:hide
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/chunklist_w307927015_…hdGhhc2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=.m3u8".
[debug][hls] playback:levels:available [Object, Object]
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/media_w307927015_b209…c2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=_297239.ts".
[debug][hls] playback:fragment:loaded Object {payload: ArrayBuffer, frag: Object, stats: Object}
XHR finished loading: GET "https://cdn01.company-name.com.tv/app-name/smil:channel.smil/media_w307927015_b209…c2g9bnRaa1RmOHBKWF9LQ2lWVjRha0VTMkw1eFBfWmRyS1lkX3ZNaU00c2ZETT0=_297240.ts".
[debug][hls] playback:fragment:loaded Object {payload: ArrayBuffer, frag: Object, stats: Object}
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate
[debug][hls] playback:settingsupdate
[debug][Container] container:settingsupdate

```

**Comment by leandromoreira** [comment] 2016-07-19 11:28
@paunadeu I'm not being able to reproduce this =/ have you double checked if the plugin is available? If no errors are shown in the initial render ? if your config is right? (without playing)

Here's a screenshot of the plugin being used.

![screen shot 2016-07-19 at 8 25 47 am](https://cloud.githubusercontent.com/assets/55913/16948334/78dd4e32-4d8a-11e6-98f2-de8518c2eecd.png)

**Comment by paunadeu** [comment] 2016-07-19 14:24
I'm see object when App is running at Cordova device (Android, iOS...) but not in a browser. 😞

**Comment by paunadeu** [comment] 2016-07-19 14:40
When I click stop, the stats show in console, but runEach not doing their work properly.

**Comment by leandromoreira** [comment] 2016-07-19 15:07
@paunadeu I'm not being able to get the same results as you therefore I think it might be something related to your environment. 

*  **have you double checked if the plugin is available?**
*  **If no errors are shown in the initial render ?** 
* **have you tested at http://cdn.clappr.io/  using a known source ?**

**Comment by paunadeu** [comment] 2016-07-19 16:28
I think it's CORS related, I see errors on initial render, but only affect to this plugin. When player destroy plugin send all stats, It's good workaround.

**Comment by leandromoreira** [comment] 2016-07-19 18:21
Nice :) can I close it @paunadeu ?

**Comment by machenmusik** [comment] 2016-08-15 22:53
I think the expected behavior is that periodic stats report should fire for all content types -- mp4, hls m3u8, shaka dash -- and my recent observation is that those do not fire if the Clappr player has autoPlay set to true, but they do if autoPlay is false and then play() is called on the player object immediately thereafter.

Given that observation, there is probably a simple fix to get correct behavior, which would be better than closing this IMO

**Closed** 2016-08-16 00:10 UTC
